name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: 24f2004781@ds.study.iitm.ac.in
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Cache with specific key and prime step
      - name: Cache Python dependencies
        id: cache-980a763
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-980a763
          restore-keys: |
            cache-

      # 4. Prime cache step that echoes cache hit/miss result
      - name: prime-cache-980a763
        run: |
          if [ "${{ steps.cache-980a763.outputs.cache-hit }}" == "true" ]; then
            echo "Cache HIT: Found cached dependencies"
          else
            echo "Cache MISS: No cached dependencies found, will prime cache"
          fi

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # 7. Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token $VERCEL_TOKEN --confirm
